<a href="https://colab.research.google.com/github/Pepcoders/Business-Analytics-Content/blob/BA/Feb_16.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Factors
labels=c('Asia','Oceania','Antarctica','Europe','Africa','Europe','North America','South America','Africa')

In [2]:
is.factor(labels)

[1] FALSE

In [6]:
factor_labels <- factor(labels)

In [7]:
is.factor(factor_labels)

[1] TRUE

In [8]:
typeof(factor_labels)

[1] "integer"

In [9]:
as.integer(factor_labels)

[1] 3 6 2 4 1 4 5 7 1

In [10]:
nlevels(factor_labels)

[1] 7

In [16]:
altitude_levels=c('High','Low',"Medium","Low",'High','Low')

In [14]:
altitude_factors=factor(altitude_levels)

In [15]:
as.integer(altitude_factors)

[1] 1 2 3 2 1 2

In [17]:
altitude_factors=factor(altitude_levels,order=TRUE,levels=c('Low','Medium','High'))

In [ ]:
altitude_factors

In [19]:
as.integer(altitude_factors)

[1] 3 1 2 1 3 1

In [20]:
#Creating Dataframes

countries_data<-data.frame(country=c('Portugal','France','UK'),
        population=c(10280000,66990000,66650000),
        EU=c(TRUE,TRUE,FALSE)
)

In [21]:
print(countries_data)

   country population    EU
1 Portugal   10280000  TRUE
2   France   66990000  TRUE
3       UK   66650000 FALSE


In [22]:
str(countries_data)

'data.frame':	3 obs. of  3 variables:
 $ country   : chr  "Portugal" "France" "UK"
 $ population: num  10280000 66990000 66650000
 $ EU        : logi  TRUE TRUE FALSE


In [23]:
countries_data<-data.frame(row.names=c('Portugal','France','UK'),   #Naming the rows
        population=c(10280000,66990000,66650000),
        EU=c(TRUE,TRUE,FALSE)
)

In [24]:
print(countries_data)

         population    EU
Portugal   10280000  TRUE
France     66990000  TRUE
UK         66650000 FALSE


In [25]:
#Indexing and modifying DF
countries_data[1,1]

[1] 10280000

In [26]:
countries_data[1,]

population EU  
Portugal 10280000   TRUE

In [27]:
countries_data[c('Portugal','France'),]

population EU  
Portugal 10280000   TRUE
France   66990000   TRUE

In [30]:
countries_data['Portugal','population'] <- 45450000 # Modify DF elements

In [31]:
print(countries_data)

         population    EU
Portugal   45450000  TRUE
France     66990000  TRUE
UK         66650000 FALSE


In [32]:
#rbind # cbind #Adding elements

countries_data<-data.frame(country=c('Portugal','France','UK'),
        population=c(10280000,66990000,66650000),
        EU=c(TRUE,TRUE,FALSE)
)

In [33]:
print(countries_data)

   country population    EU
1 Portugal   10280000  TRUE
2   France   66990000  TRUE
3       UK   66650000 FALSE


In [34]:
spain_data<-data.frame(country=c('Spain'),
        population=c(1464561231),
        EU=c(TRUE)
)

In [35]:
print(spain_data)

  country population   EU
1   Spain 1464561231 TRUE


In [37]:
countries_data<-rbind(countries_data,spain_data)

In [38]:
print(countries_data)

   country population    EU
1 Portugal   10280000  TRUE
2   France   66990000  TRUE
3       UK   66650000 FALSE
4    Spain 1464561231  TRUE


In [39]:
capitals<-c("Lisbon",'Paris','London','Madrid')

In [40]:
countries_data <-cbind(countries_data,capitals)

In [41]:
print(countries_data)

   country population    EU capitals
1 Portugal   10280000  TRUE   Lisbon
2   France   66990000  TRUE    Paris
3       UK   66650000 FALSE   London
4    Spain 1464561231  TRUE   Madrid


In [42]:
str(countries_data)

'data.frame':	4 obs. of  4 variables:
 $ country   : chr  "Portugal" "France" "UK" "Spain"
 $ population: num  1.03e+07 6.70e+07 6.66e+07 1.46e+09
 $ EU        : logi  TRUE TRUE FALSE TRUE
 $ capitals  : chr  "Lisbon" "Paris" "London" "Madrid"


In [45]:
#Removing elements from DF
countries_data<-countries_data[-4,] #remove rows

In [46]:
print(countries_data)

   country population    EU capitals
1 Portugal   10280000  TRUE   Lisbon
2   France   66990000  TRUE    Paris
3       UK   66650000 FALSE   London


In [48]:
countries_data[,'EU']<-NULL #Remove columns

In [49]:
print(countries_data)

   country population capitals
1 Portugal   10280000   Lisbon
2   France   66990000    Paris
3       UK   66650000   London


In [50]:
summary(countries_data)

   country            population         capitals        
 Length:3           Min.   :10280000   Length:3          
 Class :character   1st Qu.:38465000   Class :character  
 Mode  :character   Median :66650000   Mode  :character  
                    Mean   :47973333                     
                    3rd Qu.:66820000                     
                    Max.   :66990000                     

In [51]:
#Creating lists 
vec=c(1,2,"3")
typeof(vec)

[1] "character"

In [52]:
my_list=list(1,2,"3")

In [53]:
typeof(my_list)

[1] "list"

In [55]:
multi_object <- list(c(1,2,3),
array(1:4,dim=c(2,2)),
TRUE)

In [56]:
print(multi_object)

[[1]]
[1] 1 2 3

[[2]]
     [,1] [,2]
[1,]    1    3
[2,]    2    4

[[3]]
[1] TRUE



In [57]:
#Names property
names(multi_object)<-c("Vector","Array","logical")

In [58]:
print(multi_object)

$Vector
[1] 1 2 3

$Array
     [,1] [,2]
[1,]    1    3
[2,]    2    4

$logical
[1] TRUE



In [60]:
length(multi_object)

[1] 3

In [61]:
str(multi_object)

List of 3
 $ Vector : num [1:3] 1 2 3
 $ Array  : int [1:2, 1:2] 1 2 3 4
 $ logical: logi TRUE


In [62]:
#Assigning names automatically
multi_object<-list("Vector"=c(1,2,3),
"Array"=array(1:4,dim=c(2,2)),
"Logical"=TRUE)

In [63]:
print(multi_object)

$Vector
[1] 1 2 3

$Array
     [,1] [,2]
[1,]    1    3
[2,]    2    4

$Logical
[1] TRUE



In [64]:
#Indexing Lists
multi_object[1]  #Accesing the sub-list

$Vector
[1] 1 2 3

In [65]:
multi_object[1][1]

$Vector
[1] 1 2 3

In [69]:
vect=c(1,2,3)
vect

In [70]:
multi_object[1]

[1] 1 2 3

In [67]:
multi_object[[1]]#Accessing underlying values

[1] 1 2 3

In [68]:
multi_object[[1]][1]

[1] 1

In [71]:
multi_object[[2]][2,2]

[1] 4

In [72]:
multi_object[c(1,2)]

$Vector
[1] 1 2 3

$Array
     [,1] [,2]
[1,]    1    3
[2,]    2    4

In [73]:
multi_object[['Array']]

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [74]:
multi_object$Vector

[1] 1 2 3

In [75]:
#Changing and adding elements to list 

example_list= list(c('a','b','c'),array(1:10,dim=c(2,5)))

In [77]:
example_list[[3]] <-c(1,2,3) #adding new element to list

In [80]:
example_list

[[1]]
[1] "a" "b" "c"

[[2]]
[1] TRUE

[[3]]
[1] 1 2 3

In [86]:
example_list[2]<- TRUE # Replace/Overwrite

In [81]:
length(example_list)

[1] 3

In [82]:
example_list[[10]] <-c(8,9,10)

In [83]:
length(example_list)

[1] 10

In [84]:
print(example_list)

[[1]]
[1] "a" "b" "c"

[[2]]
[1] TRUE

[[3]]
[1] 1 2 3

[[4]]
NULL

[[5]]
NULL

[[6]]
NULL

[[7]]
NULL

[[8]]
NULL

[[9]]
NULL

[[10]]
[1]  8  9 10

